/** Real browser verification. Install Playwright separately; see README. */
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import path from 'node:path';
const playwright = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
const browser = await playwright.chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) });
const base = process.env.TEST_URL || 'http://127.0.0.1:3000';
const results = [];
const started = Date.now();
await mkdir('test-results', { recursive: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const page = await context.newPage();
page.setDefaultTimeout(10000);
const errors = []; page.on('pageerror', error => errors.push(error.message));
const mark = label => { results.push(label); console.log(`PASS ${label}`); };
const click = async name => { await page.getByRole('button', { name, exact: true }).click(); await idle(); };
const idle = async () => page.waitForFunction(() => document.querySelector('#app')?.getAttribute('aria-busy') === 'false');
const stored = () => page.evaluate(() => JSON.parse(localStorage.getItem('briefly.mvp.v1')));
const official = async value => assert.equal(await page.getByTestId('official-score').textContent(), String(value));
async function fillProposal() {
  await page.getByLabel('Solution idea', { exact: false }).fill('Build a searchable order dashboard with clear status labels.');
  await page.getByLabel('Implementation plan', { exact: false }).fill('Review the synthetic order data, implement status search, and test with five sample orders.');
  await page.getByLabel('Estimated duration / delivery term', { exact: false }).fill('4 hours');
  await page.getByLabel('Prototype link', { exact: false }).fill('https://example.com/demo-order-dashboard');
}
try {
  await page.goto(base); await idle();
  await page.getByRole('heading', { name: 'Good ideas start with a clear brief.' }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  assert.equal(await page.locator('.task-tile').count(), 5);
  await page.screenshot({ path: 'test-results/workspace.png', fullPage: true });
  mark('Production application loads with seeded workspace and working navigation');
  await click('Create a task');
  await page.getByLabel('Your rough description').fill('Make an app');
  await page.getByLabel('Topic / industry').selectOption('Retail');
  await click('Analyze my brief');
  assert.match(await page.getByRole('alert').innerText(), /four words/);
  assert.equal(await page.getByLabel('Your rough description').inputValue(), 'Make an app');
  mark('Weak-description error is clear and preserves entered data');
  await click('Use weak demo example');
  await page.getByRole('button', { name: 'Analyze my brief', exact: true }).click();
  await page.getByText('Analyzing completeness and preparing questions…', { exact: true }).waitFor();
  await idle();
  assert.ok(await page.locator('form textarea').count() >= 3);
  assert.match(await page.locator('.source-callout').innerText(), /track orders/);
  await click('Add prepared demo answers');
  await click('Generate editable card');
  await official(0);
  assert.equal(await page.locator('textarea[name="contact"]').inputValue(), '');
  assert.equal(await page.locator('textarea[name="data"]').inputValue(), '');
  assert.equal(await page.locator('textarea[name="success"]').inputValue(), '');
  await page.getByLabel('Task title', { exact: false }).fill('Track shop orders with confidence');
  mark('Analysis loading, relevant questions, exact-source generation and empty unsupported facts');
  await click('Confirm card & calculate rating');
  assert.match(await page.getByRole('alert').innerText(), /Confirm that you reviewed/);
  await official(0);
  await page.getByRole('checkbox').check();
  await click('Confirm card & calculate rating');
  await official(45);
  assert.equal(await page.locator('.breakdown details').count(), 7);
  await page.locator('.breakdown summary').first().click();
  assert.match(await page.locator('.field-reason').first().innerText(), /manually confirmed/);
  assert.ok(await page.locator('.improve li').count() > 0);
  mark('Manual attestation gate, initial 45/100 Working rating, seven categories and improvement guidance');
  const newTask = (await stored()).tasks.find(t => t.original.includes('track orders in our shop') && t.confirmed);
  assert.ok(newTask);
  await click('Edit & improve');
  await click('Insert complete synthetic demo details');
  await official(45);
  await click('Save unconfirmed draft');
  await official(45);
  await click('Back to workspace');
  await page.locator(`[data-action="open"][data-id="${newTask.id}"]`).first().click();
  await click('Publish task');
  assert.match(await page.getByRole('alert').innerText(), /manually confirm/);
  await click('Edit & improve');
  await page.getByRole('checkbox').check();
  await click('Confirm card & calculate rating');
  await official(100);
  assert.match(await page.locator('.complete-message').innerText(), /No missing fields/);
  await click('Publish task');
  assert.match(await page.locator('.publication').innerText(), /Published/);
  await page.getByRole('heading', { name: 'No proposals yet', exact: true }).waitFor();
  mark('Saved unconfirmed edits preserve official score and block publication; confirmed improvements reach 100 and publish');
  await click('Team');
  await click('Task catalog');
  assert.equal(await page.locator('.task-tile').count(), 6);
  await page.getByLabel('Topic', { exact: true }).selectOption('Retail');
  await page.getByLabel('Readiness', { exact: true }).selectOption('Priority');
  assert.equal(await page.locator('.task-tile').count(), 2);
  await page.getByLabel('Sort by').selectOption('asc');
  await page.screenshot({ path: 'test-results/catalog.png', fullPage: true });
  await page.locator(`[data-action="open"][data-id="${newTask.id}"]`).first().click();
  await fillProposal();
  await page.getByLabel('Solution idea', { exact: false }).fill('TBD');
  await click('Submit proposal');
  assert.match(await page.getByRole('alert').innerText(), /meaningful solution idea/);
  assert.equal(await page.getByLabel('Prototype link', { exact: false }).inputValue(), 'https://example.com/demo-order-dashboard');
  await fillProposal();
  await click('Submit proposal');
  assert.match(await page.locator('.proposal-card').last().innerText(), /Pending/);
  mark('Complete catalog, both filters, sorting, proposal validation, data retention and successful submission');
  await click('Business');
  await page.locator(`[data-action="open"][data-id="${newTask.id}"]`).first().click();
  await click('Accept proposal');
  assert.equal((await stored()).progress.length, 0);
  await page.getByText('Confirm an actual milestone · +10 demo points', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Completed milestone', exact: false }).fill('Searchable order prototype demonstrated');
  await page.getByLabel('Evidence of actual progress reviewed').fill('I reviewed the working prototype and verified status lookup on five synthetic orders.');
  await page.getByRole('checkbox').check();
  await click('Confirm progress & award points');
  assert.equal((await stored()).progress[0].points, 10);
  await page.evaluate(() => { document.activeElement?.blur(); window.scrollTo(0, 0); });
  await page.screenshot({ path: 'test-results/confirmed-task.png', fullPage: true });
  await click('Team profiles');
  assert.match(await page.locator('.team-profile').first().innerText(), /10 progress points/);
  mark('Manual acceptance awards zero points; actual attested milestone awards 10 and appears on team profile');
  await page.reload(); await idle();
  const persisted = await stored();
  assert.equal(persisted.tasks.find(t => t.id === newTask.id).published, true);
  assert.equal(persisted.progress.length, 1);
  assert.equal(persisted.proposals.find(p => p.taskId === newTask.id).status, 'Accepted');
  mark('Publication, manual decision and progress survive a real page reload');
  await click('Task catalog');
  await page.getByLabel('Readiness', { exact: true }).selectOption('Draft');
  assert.equal(await page.locator('.task-tile').count(), 1);
  await click('Team');
  await page.locator('[data-action="open"][data-id="task-community"]').first().click();
  await official(10);
  await fillProposal(); await click('Submit proposal');
  assert.ok((await stored()).proposals.some(p => p.taskId === 'task-community' && p.teamId === 'team-orbit'));
  mark('Low-rated published task remains visible and accepts a complete team proposal');
  await click('Business');
  await page.locator('[data-action="open"][data-id="task-orders"]').first().click();
  await page.locator('[data-proposal="proposal-1"] [data-action="accept"]').click(); await idle();
  assert.equal((await stored()).proposals.find(p => p.id === 'proposal-2').status, 'Pending');
  await page.locator('[data-proposal="proposal-2"] [data-action="accept"]').click(); await idle();
  assert.equal((await stored()).proposals.filter(p => p.taskId === 'task-orders' && p.status === 'Accepted').length, 2);
  await page.locator('[data-proposal="proposal-1"] [data-action="reject"]').click(); await idle();
  await page.locator('[data-proposal="proposal-2"] [data-action="reject"]').click(); await idle();
  assert.equal((await stored()).proposals.filter(p => p.taskId === 'task-orders' && p.status === 'Accepted').length, 0);
  mark('Business compares proposals and chooses one, multiple or zero teams with independent persisted decisions');
  await click('Task catalog');
  await page.getByLabel('Topic', { exact: true }).selectOption('Retail');
  await page.getByLabel('Readiness', { exact: true }).selectOption('Draft');
  await page.getByRole('heading', { name: 'No tasks match these filters' }).waitFor();
  mark('Filtered no-results state is meaningful');
  await click('My workspace'); await click('Create a task'); await click('Use weak demo example');
  await page.route('**/api/analyze', route => route.fulfill({ status: 200, contentType: 'application/json', body: '{"card":{"contact":"invented@example.com"}}' }));
  await click('Analyze my brief');
  assert.match(await page.locator('.notice').innerText(), /local assistant/);
  await page.unroute('**/api/analyze');
  mark('Malformed browser API response falls back locally without inventing facts');
  await click('Demo guide');
  await page.getByRole('heading', { name: 'From “we need help” to “let’s build”.' }).waitFor();
  await click('Start the demo');
  assert.match(await page.getByLabel('Your rough description').inputValue(), /track orders/);
  mark('In-app five-minute guide and prepared demo entry point work');
  assert.deepEqual(errors, []);
  mark('No uncaught JavaScript errors in the complete live journey');

  // Separate isolated sessions exercise recoverable storage failures and empty states.
  const broken = await browser.newContext();
  await broken.addInitScript(() => localStorage.setItem('briefly.mvp.v1', '{broken-json'));
  const badPage = await broken.newPage(); await badPage.goto(base);
  await badPage.getByRole('alert').waitFor();
  assert.equal(await badPage.evaluate(() => localStorage.getItem('briefly.mvp.v1')), '{broken-json');
  await badPage.getByRole('button', { name: 'Reset demo', exact: true }).first().click();
  await badPage.getByRole('button', { name: 'Reset synthetic demo', exact: true }).click();
  assert.equal(await badPage.getByRole('alert').count(), 0);
  mark('Corrupt storage preserved and explicit reset recovers safely');
  await broken.close();

  const fullContext = await browser.newContext();
  const fullPage = await fullContext.newPage(); await fullPage.goto(base);
  await fullPage.getByRole('button', { name: 'Create a task', exact: true }).click();
  await fullPage.getByRole('button', { name: 'Use weak demo example', exact: true }).click();
  await fullPage.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('Full', 'QuotaExceededError'); }; });
  await fullPage.getByRole('button', { name: 'Analyze my brief', exact: true }).click();
  await fullPage.getByRole('alert').waitFor();
  assert.match(await fullPage.getByRole('alert').innerText(), /could not be saved/);
  assert.match(await fullPage.getByLabel('Your rough description').inputValue(), /track orders/);
  mark('Persistence failure keeps form inputs and does not claim success');
  await fullContext.close();

  const emptyContext = await browser.newContext();
  const emptyPage = await emptyContext.newPage(); await emptyPage.goto(base);
  await emptyPage.evaluate(() => { const s = JSON.parse(localStorage.getItem('briefly.mvp.v1')); s.tasks = []; s.proposals = []; s.progress = []; localStorage.setItem('briefly.mvp.v1', JSON.stringify(s)); });
  await emptyPage.reload();
  await emptyPage.getByRole('button', { name: 'Task catalog', exact: false }).first().click();
  await emptyPage.getByRole('heading', { name: 'The catalog is waiting for its first task' }).waitFor();
  await emptyPage.getByRole('button', { name: 'Team', exact: true }).click();
  await emptyPage.getByRole('button', { name: 'My workspace', exact: true }).click();
  await emptyPage.getByRole('heading', { name: 'Your next collaboration starts with a proposal' }).waitFor();
  mark('Empty catalog and empty team-history states render correctly');
  await emptyContext.close();
  const durationSeconds = Math.round((Date.now() - started) / 1000);
  await writeFile('test-results/browser-report.json', JSON.stringify({ passed: results.length, durationSeconds, checks: results, pageErrors: errors }, null, 2));
  console.log(`\n${results.length} browser checks passed in ${durationSeconds}s. Artifacts: ${path.resolve('test-results')}`);
} catch (error) {
  await page.screenshot({ path: 'test-results/failure.png', fullPage: true });
  await writeFile('test-results/browser-failure.txt', `${error.stack}\n\n${await page.locator('body').innerText()}`);
  throw error;
} finally { await context.close(); await browser.close(); }
